import { createFileRoute, notFound, useNavigate } from '@tanstack/react-router'
import { useStore } from '../features/catalogue/context'
import { cataloguePage } from '../features/catalogue/model'
import { catalogueSearch } from '../features/catalogue/functions'
import { useHydrated } from '../components/useHydrated'
import { ProductCard } from '../features/catalogue/ProductCard'
export const Route = createFileRoute('/$department/shop')({ validateSearch: search => catalogueSearch.parse(search), beforeLoad: ({ context, params }) => { if (context.store && !context.store.departments.some(d => d.slug === params.department)) throw notFound() }, component: Shop })
function Shop() {
  const { department } = Route.useParams(), search = Route.useSearch(), navigate = useNavigate({ from: Route.fullPath }), store = useStore()
  const d = store.departments.find(item => item.slug === department)
  if (!d) throw notFound()
  const hydrated = useHydrated()
  const result = cataloguePage(store.products, { ...search, department })
  function toggle(key: string, value: string) { const chosen = search.filters[key] ?? []; void navigate({ search: { ...search, page: 1, filters: { ...search.filters, [key]: chosen.includes(value) ? chosen.filter(v=>v!==value) : [...chosen,value] } } }) }
  return <main id="main" className="container"><div className="shop-heading"><div><p className="muted">{d.name}</p><h1>{search.category || 'Shop the collection'}</h1></div><p>{result.total} {result.total===1?'item':'items'}</p></div><form className="search-form" onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); void navigate({ search: { ...search, q: String(form.get('q') || ''), page: 1 } }) }}><label htmlFor="search">Search products or brands</label><div><input id="search" name="q" defaultValue={search.q ?? ''} maxLength={100}/><button type="submit" disabled={!hydrated}>Search</button></div></form><div className="shop-layout"><aside className="filters" aria-label="Product filters"><div className="section-heading"><h2>Filter</h2><button className="text-button" onClick={() => void navigate({ search: { sort: 'featured', page: 1, filters: {} } })}>Clear all</button></div>{Object.entries(result.facets).map(([key, values]) => <fieldset key={key} disabled={!hydrated}><legend>{key}</legend>{values.map(({ value, count }) => <label key={value}><input type="checkbox" checked={search.filters[key]?.includes(value) ?? false} aria-label={`${key} ${value}`} onChange={()=>toggle(key,value)}/><span>{value}</span><small>{count}</small></label>)}</fieldset>)}</aside><section aria-label="Products"><div className="sort-row"><label>Sort by <select value={search.sort} onChange={e=>void navigate({ search: { ...search, sort: e.target.value as typeof search.sort, page: 1 } })}><option value="featured">Featured</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select></label></div>{result.items.length ? <div className="product-grid">{result.items.map(p=><ProductCard key={p.id} product={p}/>)}</div> : <div className="empty-state"><h2>No matching products</h2><p>Try removing a filter or changing your search.</p></div>}<nav className="pagination" aria-label="Product pages"><button disabled={search.page===1} onClick={()=>void navigate({ search: { ...search, page: search.page-1 } })}>Previous</button><span>Page {search.page}</span><button disabled={search.page*result.pageSize>=result.total} onClick={()=>void navigate({ search: { ...search, page: search.page+1 } })}>Next</button></nav></section></div></main>
}
