import { createFileRoute, Link } from '@tanstack/react-router'
import {checkoutAvailability} from '../features/commerce/functions'
import { useCart } from '../features/cart/context'
import { useStore } from '../features/catalogue/context'
import { formatMoney } from '../features/catalogue/model'
export const Route = createFileRoute('/bag')({ loader:()=>checkoutAvailability(), component: Bag, head: () => ({ meta: [{ title: 'Shopping bag | The Avenue Thirty' }] }) })
function Bag() {
  const enabled=Route.useLoaderData(),cart=useCart(), store=useStore()
  const lines=cart.lines.map(line=>{const product=store.products.find(p=>p.variants.some(v=>v.sku===line.sku));return {...line,product,variant:product?.variants.find(v=>v.sku===line.sku)}})
  const total=lines.reduce((sum,line)=>sum+(line.variant?.priceMinor ?? 0)*line.quantity,0)
  return <main id="main" className="container"><h1>Your bag</h1>{lines.length ? <div className="bag-layout"><div>{lines.map(line=><article className="bag-row" key={line.sku}><div><h2>{line.product ? <Link to="/products/$slug" params={{slug:line.product.slug}}>{line.product.name}</Link>:'Item unavailable'}</h2><p className="muted">{line.sku}</p><p>{line.variant ? Object.values(line.variant.options).join(' / '):'Remove this item before checkout.'}</p>{line.variant&&!line.variant.available&&<p>Currently unavailable</p>}<button className="text-button" onClick={()=>cart.setQuantity(line.sku,0)}>Remove</button></div><div><label>Quantity <select aria-label={`Quantity for ${line.sku}`} value={line.quantity} onChange={e=>cart.setQuantity(line.sku,Number(e.target.value))}>{Array.from({length:99},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label><p>{line.variant ? formatMoney(line.variant.priceMinor*line.quantity):'Unavailable'}</p></div></article>)}</div><aside className="bag-summary"><h2>Order summary</h2><div><span>Subtotal</span><strong>{formatMoney(total)}</strong></div><p>Delivery and final availability will be confirmed at checkout.</p><Link to="/checkout" className="button">{enabled?'Proceed to test checkout':'Checkout information'}</Link><p className="muted">{enabled?'Development test orders only.':'This preview does not accept orders.'}</p><p><a href="https://wa.me/923331458843" target="_blank" rel="noopener noreferrer" className="text-button">Ask about your bag on WhatsApp</a></p><p className="muted">Opens WhatsApp. A chat does not place an order or reserve stock.</p></aside></div>:<div className="empty-state"><h2>Your bag is empty</h2><p>Explore a department to find something you like.</p><Link to="/" className="button">Explore the store</Link></div>}</main>
}
