import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import {useEffect,useState} from 'react'
import {useHydrated} from '../components/useHydrated'
import {useCart} from '../features/cart/context'
import {checkoutAvailability,createOrder} from '../features/commerce/functions'
import {orderInput,type OrderInput} from '../features/commerce/model'
export const Route = createFileRoute('/checkout')({loader:()=>checkoutAvailability(),component:Checkout,head:()=>({meta:[{name:'robots',content:'noindex'},{name:'referrer',content:'no-referrer'}]})})
type Attempt={key:string;input:OrderInput}
const storage='avenue-pending-order-v2'
function Checkout(){const hydrated=useHydrated(),enabled=Route.useLoaderData(),cart=useCart(),navigate=useNavigate(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<Attempt|null>(null)
 useEffect(()=>{try{const raw=sessionStorage.getItem(storage);if(raw){const value=JSON.parse(raw);if(typeof value.key==='string'&&/^[a-f0-9-]{36}$/.test(value.key))setPending({key:value.key,input:orderInput.parse(value.input)})}}catch{sessionStorage.removeItem(storage)}},[])
 async function send(attempt:Attempt){if(busy)return;setBusy(true);setError('');try{sessionStorage.setItem(storage,JSON.stringify(attempt));setPending(attempt);const result=await createOrder({data:attempt});if(result.ok){sessionStorage.removeItem(storage);setPending(null);attempt.input.lines.forEach(ordered=>{const current=cart.lines.find(line=>line.sku===ordered.sku);if(current)cart.setQuantity(ordered.sku,Math.max(0,current.quantity-ordered.quantity))});await navigate({to:'/orders/$receipt',params:{receipt:result.receipt}})}else setError(result.message)}catch{setError('We could not confirm the result. Retry this attempt to check whether the order was saved.')}finally{setBusy(false)}}
 if(!enabled)return <main id="main" className="container narrow"><h1>Checkout is not open yet</h1><p>This is a storefront preview. No order has been placed and no payment will be collected.</p><p>Your bag is saved on this device while we prepare the shopping experience.</p><Link to="/bag" className="button">Return to your bag</Link></main>
 return <main id="main" className="container narrow"><h1>Development checkout</h1><p>Test orders only. Cash on delivery is recorded for testing. No payment, message or delivery will be initiated.</p>{pending?<section><h2>Recover your previous attempt</h2><p>Retry the saved details to recover the same order number. Details are kept in this browser tab until the attempt is cleared.</p><button className="button" disabled={busy} onClick={()=>send(pending)}>Retry previous attempt</button><p>Starting a new attempt can create another order if the previous one was saved. Recover it first.</p><button disabled={busy} onClick={()=>{sessionStorage.removeItem(storage);setPending(null);setError('')}}>Clear attempt and edit details</button></section>:!cart.lines.length?<Link to="/bag">Your bag is empty</Link>:<form method="post" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);const result=orderInput.safeParse({name:String(form.get('name')),phone:String(form.get('phone')),address:{line1:String(form.get('address')),city:String(form.get('city')),postalCode:String(form.get('postalCode')),country:'PK',email:String(form.get('email')||'').trim().toLowerCase()},lines:cart.lines});if(!result.success){setError('Check your details and quantities. Use an international phone number, for example +923001234567.');return}void send({key:crypto.randomUUID(),input:result.data})}}>{[['name','Full name'],['phone','Phone number'],['address','Street address'],['city','City'],['postalCode','Postal code'],['email','Email (optional, order updates)']].map(([name,label])=><p key={name}><label>{label}<input name={name} type={name==='email'?'email':'text'} required={name!=='postalCode'&&name!=='email'} autoComplete={name==='name'?'name':name==='phone'?'tel':name==='address'?'street-address':name==='city'?'address-level2':'postal-code'} maxLength={name==='address'?200:100}/></label></p>)}<p>Pakistan. Delivery charge: PKR 0 for this test.</p><button className="button" disabled={busy||!hydrated}>{busy?'Placing test order…':'Place test COD order'}</button></form>}{error&&<p role="alert">{error}</p>}</main>}
