import { test, expect } from '@playwright/test'
test('department URLs and product variant cart persist across navigation and reload', async ({ page }) => {
  await page.goto('/women')
  await expect(page.getByRole('heading', { name: 'Women', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Everyday cotton shirt', exact: true }).first().click()
  await expect(page.getByRole('button', { name: 'Add to bag' })).toBeDisabled()
  await page.getByRole('button', { name: 'Colour: Red', exact: true }).click()
  await page.getByRole('button', { name: 'Size: S', exact: true }).click()
  await page.getByRole('button', { name: 'Add to bag' }).click()
  await page.getByRole('link', { name: /Bag \(1\)/ }).click()
  await expect(page.getByText('DEMO-SHIRT-RS', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('DEMO-SHIRT-RS', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Technology', exact: true }).first().click()
  await expect(page.getByRole('link', { name: /Bag \(1\)/ })).toBeVisible()
})
test('unavailable combinations filter out and filters survive reload', async ({ page }) => {
  await page.goto('/women/shop')
  await page.getByLabel('Colour Red').click()
  await expect(page).toHaveURL(/filters=/)
  await expect(page.getByLabel('Colour Red')).toBeChecked()
  await page.reload()
  await expect(page.getByLabel('Colour Red')).toBeChecked()
  await expect(page.getByRole('link', { name: 'Everyday cotton shirt', exact: true })).toBeVisible()
  await expect(page.getByLabel('Size L')).toHaveCount(0)
})
test('draft routes do not disclose products and checkout is explicitly unavailable', async ({ page }) => {
  await page.goto('/products/unreleased-shirt')
  await expect(page.getByRole('heading', { name: 'Page not found' })).toBeVisible()
  await page.goto('/checkout')
  await expect(page.getByRole('heading', { name: 'Checkout is not open yet' })).toBeVisible()
})
test('supplier application preview never pretends it submitted an application', async ({ page }) => {
  await page.goto('/sell')
  await expect(page.getByRole('heading', { name: 'Sell on The Avenue Thirty' })).toBeVisible()
  await expect(page.getByText('Applications are not open yet.', { exact: true })).toBeVisible()
})
test('published CMS pages render and unknown pages return not found', async({page})=>{
 await page.goto('/pages/about')
 await expect(page.getByRole('heading',{name:'About The Avenue Thirty',exact:true})).toBeVisible()
 await expect(page.getByRole('heading',{name:'A considered destination'})).toBeVisible()
 await page.goto('/pages/unpublished')
 await expect(page.getByRole('heading',{name:'Page not found'})).toBeVisible()
})
