import {describe,expect,it} from 'vitest'
import {StaffSessions} from '../../src/server/staff-access'
const admin={id:'admin-id',status:'active',policies:[],role:{policies:[{policy:{admin_access:true}}]}}
describe('staff sessions',()=>{
 it('keeps tokens server-side, rechecks current authority, and expires sessions',async()=>{let authorised=true,now=100;const sessions=new StaffSessions(async()=>({token:'private-token',expiresMs:10000}),async token=>{expect(token).toBe('private-token');return authorised?admin:{...admin,role:null}},()=>now);const session=await sessions.login('staff@example.invalid','password');expect(session).not.toContain('private-token');expect((await sessions.authorise(session)).actor).toBe('admin-id');authorised=false;await expect(sessions.authorise(session)).rejects.toThrow('Staff authentication required');authorised=true;now=11000;await expect(sessions.authorise(session)).rejects.toThrow('Staff authentication required')})
 it('rejects nonadministrators and rate limits repeated login attempts',async()=>{const sessions=new StaffSessions(async()=>{throw new Error('Invalid login')},async()=>admin);for(let i=0;i<5;i++)await expect(sessions.login('staff@example.invalid','wrong')).rejects.toThrow();await expect(sessions.login('staff@example.invalid','wrong')).rejects.toThrow('Please wait before trying again')})
 it('revokes a session on logout',async()=>{const sessions=new StaffSessions(async()=>({token:'token',expiresMs:10000}),async()=>admin);const id=await sessions.login('staff@example.invalid','password');sessions.logout(id);await expect(sessions.authorise(id)).rejects.toThrow('Staff authentication required')})
})
it('does not lock every administrator when the attempt cache reaches capacity',async()=>{const sessions=new StaffSessions(async email=>{if(email==='admin@example.invalid')return {token:'token',expiresMs:10000};throw new Error()},async()=>admin);for(let i=0;i<100;i++)await sessions.login(`unknown-${i}@example.invalid`,'wrong').catch(()=>{});expect(await sessions.login('admin@example.invalid','correct')).toMatch(/^[a-f0-9]{64}$/)})
it('preserves throttled account windows when other accounts are attempted',async()=>{const sessions=new StaffSessions(async()=>{throw new Error()},async()=>admin);for(let i=0;i<5;i++)await sessions.login('locked@example.invalid','wrong').catch(()=>{});for(let i=0;i<120;i++)await sessions.login(`other-${i}@example.invalid`,'wrong').catch(()=>{});await expect(sessions.login('locked@example.invalid','wrong')).rejects.toThrow('Please wait before trying again')})
it('rejects a cross-tab staff identity change before placing an order',async()=>{const {assertStaffOwner}=await import('../../src/server/staff-access');expect(()=>assertStaffOwner('staff-b','staff-a')).toThrow('Staff authentication required');expect(()=>assertStaffOwner('staff-a','staff-a')).not.toThrow()})
