import { Link, useLocation } from '@tanstack/react-router'
import { ArrowUpRight, ShoppingBag } from 'lucide-react'
import type { ReactNode } from 'react'
import { useStore } from '../features/catalogue/context'
import { useCart } from '../features/cart/context'
export function Shell({ children }: { children: ReactNode }) {
  const store = useStore(), cart = useCart(), location = useLocation()
  return <><div className="preview-strip">Store preview. {store.fixturePreview ? 'Sample catalogue. ' : ''}{store.checkoutEnabled?'Development test orders only. No payments or deliveries.':'Orders are not being accepted.'}</div><header className="site-header"><div className="header-main"><Link to="/" className="wordmark" aria-label="The Avenue Thirty home">THE AVENUE <span>THIRTY</span></Link><Link to="/bag" className="bag-link"><ShoppingBag size={18} aria-hidden="true" />Bag ({cart.lines.reduce((n,l) => n+l.quantity,0)})</Link></div><nav aria-label="Departments" className="department-nav">{store.departments.map(d => <Link key={d.slug} to="/$department" params={{ department: d.slug }} aria-current={location.pathname.split('/')[1] === d.slug ? 'page' : undefined}>{d.name}</Link>)}</nav>{store.content?.navigation.some(n=>n.department===null || n.department===location.pathname.split('/')[1]) && <nav className="subnav container" aria-label="Featured navigation">{store.content.navigation.filter(n=>n.department===null || n.department===location.pathname.split('/')[1]).map((n,i)=><a key={i} href={n.path}>{n.label}</a>)}</nav>}</header>{children}<footer className="site-footer"><div><Link to="/" className="wordmark small">THE AVENUE THIRTY</Link><p>{store.content?.settings.footerText || 'The destination for fashion, tech and living.'}</p>{store.content?.pages.filter(p=>!p.department).map(p=><Link key={p.slug} to="/pages/$slug" params={{slug:p.slug}}>{p.name}</Link>)}</div><Link to="/sell">Sell on The Avenue Thirty <ArrowUpRight size={16} aria-hidden="true" /></Link><p className="footer-note">Pakistan · PKR</p></footer></>
}
