/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BagRouteImport } from './routes/bag'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as SellRouteImport } from './routes/sell'
import { Route as DepartmentIndexRouteImport } from './routes/$department.index'
import { Route as DepartmentShopRouteImport } from './routes/$department.shop'
import { Route as OrdersReceiptRouteImport } from './routes/orders.$receipt'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as StaffOrdersRouteImport } from './routes/staff.orders'
import { Route as StaffInvoicesIdRouteImport } from './routes/staff.invoices.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentIndexRoute = DepartmentIndexRouteImport.update({
  id: '/$department/',
  path: '/$department/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentShopRoute = DepartmentShopRouteImport.update({
  id: '/$department/shop',
  path: '/$department/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersReceiptRoute = OrdersReceiptRouteImport.update({
  id: '/orders/$receipt',
  path: '/orders/$receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffOrdersRoute = StaffOrdersRouteImport.update({
  id: '/staff/orders',
  path: '/staff/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffInvoicesIdRoute = StaffInvoicesIdRouteImport.update({
  id: '/staff/invoices/$id',
  path: '/staff/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/sell': typeof SellRoute
  '/$department/shop': typeof DepartmentShopRoute
  '/orders/$receipt': typeof OrdersReceiptRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/$department/': typeof DepartmentIndexRoute
  '/staff/invoices/$id': typeof StaffInvoicesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/sell': typeof SellRoute
  '/$department/shop': typeof DepartmentShopRoute
  '/orders/$receipt': typeof OrdersReceiptRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/$department': typeof DepartmentIndexRoute
  '/staff/invoices/$id': typeof StaffInvoicesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/sell': typeof SellRoute
  '/$department/shop': typeof DepartmentShopRoute
  '/orders/$receipt': typeof OrdersReceiptRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/$department/': typeof DepartmentIndexRoute
  '/staff/invoices/$id': typeof StaffInvoicesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bag'
    | '/checkout'
    | '/sell'
    | '/$department/shop'
    | '/orders/$receipt'
    | '/pages/$slug'
    | '/products/$slug'
    | '/staff/orders'
    | '/$department/'
    | '/staff/invoices/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bag'
    | '/checkout'
    | '/sell'
    | '/$department/shop'
    | '/orders/$receipt'
    | '/pages/$slug'
    | '/products/$slug'
    | '/staff/orders'
    | '/$department'
    | '/staff/invoices/$id'
  id:
    | '__root__'
    | '/'
    | '/bag'
    | '/checkout'
    | '/sell'
    | '/$department/shop'
    | '/orders/$receipt'
    | '/pages/$slug'
    | '/products/$slug'
    | '/staff/orders'
    | '/$department/'
    | '/staff/invoices/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BagRoute: typeof BagRoute
  CheckoutRoute: typeof CheckoutRoute
  SellRoute: typeof SellRoute
  DepartmentShopRoute: typeof DepartmentShopRoute
  OrdersReceiptRoute: typeof OrdersReceiptRoute
  PagesSlugRoute: typeof PagesSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  StaffOrdersRoute: typeof StaffOrdersRoute
  DepartmentIndexRoute: typeof DepartmentIndexRoute
  StaffInvoicesIdRoute: typeof StaffInvoicesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$department/': {
      id: '/$department/'
      path: '/$department'
      fullPath: '/$department/'
      preLoaderRoute: typeof DepartmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$department/shop': {
      id: '/$department/shop'
      path: '/$department/shop'
      fullPath: '/$department/shop'
      preLoaderRoute: typeof DepartmentShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$receipt': {
      id: '/orders/$receipt'
      path: '/orders/$receipt'
      fullPath: '/orders/$receipt'
      preLoaderRoute: typeof OrdersReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/orders': {
      id: '/staff/orders'
      path: '/staff/orders'
      fullPath: '/staff/orders'
      preLoaderRoute: typeof StaffOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/invoices/$id': {
      id: '/staff/invoices/$id'
      path: '/staff/invoices/$id'
      fullPath: '/staff/invoices/$id'
      preLoaderRoute: typeof StaffInvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BagRoute: BagRoute,
  CheckoutRoute: CheckoutRoute,
  SellRoute: SellRoute,
  DepartmentShopRoute: DepartmentShopRoute,
  OrdersReceiptRoute: OrdersReceiptRoute,
  PagesSlugRoute: PagesSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  StaffOrdersRoute: StaffOrdersRoute,
  DepartmentIndexRoute: DepartmentIndexRoute,
  StaffInvoicesIdRoute: StaffInvoicesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
